### ISSUE TITLE
Ternary ops

### ISSUE THREAD

**Issue by joaomilho** [KyleAMathews/cjsx-loader#5]
So I've tried to use cjsx-loader in an existing project. First thing is that I had to remove `s of all components. Then it complained about ternary operators. Do you have any clue how to keep 'em instead of moving them to a method (which in many cases decreases readability)?

**Comment by KyleAMathews** [comment]
Can you add a sample of the code which is causing problems?

**Comment by joaomilho** [comment]
```coffee
Whatever = React.createClass
  render: ->
    <div>
      { this.props.something ?
        <div>A</div> :
        <div>B</div> }
     </div>
```

Hope it helps.

**Comment by KyleAMathews** [comment]
Coffeescript [doesn't have the ternary operator](http://coffeescript.org/#conditionals) actually. You could either write this using a normal if/else or with Coffeescript's one-liner version:

```coffeescript
Whatever = React.createClass
  render: ->
    <div>
      {if this.props.something then <div>A</div> else <div>B</div>}
    </div>
```

**Comment by joaomilho** [comment]
Yes, I know CS doesn't have ternaries. But for some reason, if you use both the gulp-cjsx and the ruby gem to convert react components to plain javascript, they accept them inside the XML blocks. And they do not accept the if/then/else construct.

The same way, using your loader there is an "unexpected _if_" If you use it. Please try.

**Comment by KyleAMathews** [comment]
Supporting ternaries would mean we'd be forking coffeescript... I'm not sure what gulp-cjsx or the ruby gem you're referring to are doing exactly but intermixing JS and Coffeescript syntax seems odd and error-prone.

You can always use the backtick operator if you want plain javascript.

**Comment by joaomilho** [comment]
Well, still the if doesn't work.

**Comment by KyleAMathews** [comment]
Could you copy in more of your code that's not working? My [example code above](https://github.com/KyleAMathews/cjsx-loader/issues/5#issuecomment-72523070) compiles just fine to:

```javascript
(function() {
  var Whatever;

  Whatever = React.createClass({
    render: function() {
      return React.createElement(React.DOM.div, null, (this.props.something ? React.createElement(React.DOM.div, null, "A") : React.createElement(React.DOM.div, null, "B")));
    }
  });

}).call(this);
```
