### ISSUE TITLE
coffee-react-transform 2.4.1 is broken

### ISSUE THREAD

**Issue by tomhicks-bsf** [KyleAMathews/cjsx-loader#6]
2.4.0 is OK, and 3.0.0 is problably OK (worth testing) but this uses ^2.2.1 which resolves to 2.4.1 which is deprecated because of some edge cases. It's breaking our build due to the spread operator not working correctly.

**Comment by KyleAMathews** [comment]
The latest version of cjsx-loader (1.3.0) pins coffee-react-transform to 2.4.0.

I'll make a 2.0.0 release real quick for the coffee-react-transform major version change.

**Comment by tomhicks-bsf** [comment]
@KyleAMathews Apparently it's not pinned, it's ^2.4.0: https://github.com/KyleAMathews/cjsx-loader/blob/v1.3.0/package.json

**Comment by KyleAMathews** [comment]
Ah, you're right. Missed that somehow. Published a 1.3.1 with the version pinned.

**Comment by KyleAMathews** [comment]
https://github.com/KyleAMathews/cjsx-loader/blob/v1.3.1/package.json
