### ISSUE TITLE
Question about CJSX and Coffee

### ISSUE THREAD

**Issue by dubert** [KyleAMathews/cjsx-loader#7]
Is there a reason you use [coffee-react-transform](https://github.com/jsdf/coffee-react-transform) to turn .cjsx into .coffee, and then do a second transform from .coffee into .js? As opposed to using something like [coffee-react](https://github.com/jsdf/coffee-react) which does both together in one step?

**Comment by KyleAMathews** [comment]
AFAIK coffee-react is just a wrapper for coffee-react-transform and coffeescript. It doesn't expose any API to convert from `.cjsx` all the way to `.js`.
